### ISSUE TITLE
One byte receiving issue

### ISSUE THREAD

**Issue by erik-don** [itas109/CSerialPort#11]
Could change the SerialPortWinBase.cpp line: 294 to follow?
if (comstat.cbInQue > 0) //设定字符数	original:  > 1 
Otherwise if we only have one byte receive, the library will not detect it.

**Comment by itas109** [comment]
In order to improve the reading efficiency,  number of cbInQue characters is greater than 1 by default.

you can use Funciton setMinByteReadNoify change it.

`CSerialPort::setMinByteReadNoify(unsigned int minByteReadNoify = 2)`

`CSerialPort cs;`

`cs.setMinByteReadNoify(1);`

**Comment by erik-don** [comment]
Thank you, 

BTW , after several days, I can direct write with MuYu, the input method of my computer got something wrong, and I have no right to install a new one.
