### ISSUE TITLE
使用中发现的一些问题

### ISSUE THREAD

**Issue by 858951002** [itas109/CSerialPort#17]
首先谢谢作者，最近在使用发现几个问题，希望可以改进.
1.内存泄露，在CSerialPort类的析构函数中delete p_serialPortBase可以解决，不知道可否这样做。
2.使用异步模式发送，在CSerialPortWinBase::writeData函数内，WriteFile函数执行后跳到lastError = itas109::WriteError处，导致没有办法获得发送的字节数，可是接收端已接收到正确的数据。
3.在主对话框中的CSerialPort对象刚开始可以正常发送与接收,然后close掉，再弹出的模式对话框中new一个CSerialPort可以正常发送接收，再关闭弹出对话框(有对CSerialPort的delete,close操作),这个时候回到主对话框，open原来的CSerialPort只能发送(确认过发送正常)，不能接收，弹出的对话框内CSerialPort始终工作正常（多次打开关闭），只要在弹出对话框中new过一次CSerialPort，主对话框CSerialPort就不能接收。在弹出对话框中使用主对话框的CSerialPort时正常。两个对话框中操作的是一个串口。不知道可否这样操作。vc6 mfc win7.

**Comment by itas109** [comment]
感谢反馈

**Comment by itas109** [comment]
问题1和问题2已经在主版本中修复。

问题3还在排查中，不知能够发一下代码，这样更便于问题的排查。不必全部都发，比如主界面和次级页面的初始化，关闭是需要的。

**Comment by 858951002** [comment]
我把问题3改成使用主对话框的CSerialPort，就是弹出模式对话框时传入指针，这样使用没有问题。
