### ISSUE TITLE
Get Friendly Name

### ISSUE THREAD

**Issue by quotschmacher** [itas109/CSerialPort#18]
in windows i would like to get the firendly name of the com device.

the windows device manager shows "Prolific 2313... (COM15)" and with your library i'm only able to get "COM15".

is there any way to get the "Prolific 2313..." part?

**Comment by itas109** [comment]
It is a good ideal. I need some time to do it.

**Comment by itas109** [comment]
hi,quotschmacher
add Function CSerialPortInfo::availableFriendlyPorts (Only windows), return firendly name like "COM1 Prolific USB-to-Serial Comm Port"
You can try it.

**Comment by quotschmacher** [comment]
with your new version i get an unresolved reference error, as soon as i use the new function.

> Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol ""public: static class std::list<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > __cdecl itas109::CSerialPortInfo::availableFriendlyPorts(void)" (?availableFriendlyPorts@CSerialPortInfo@itas109@@SA?AV?$list@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@XZ)" in Funktion ""private: void __thiscall NaClConfiguratorApplication::ScanComPorts(void)" (?ScanComPorts@NaClConfiguratorApplication@@AAEXXZ)".

i only use your "src"-fodler in my project and exchanged this. i'm compiling using 32bit release, vs 2017 under win10 x64

**Comment by itas109** [comment]
I'm run vs 2017 under win10 x64. But it works.
 you could try  use :  `CSerialPort\Demo\CommNoGui\compile-MSVC.bat`

**Comment by quotschmacher** [comment]
i had to extend my linked libraries with `setupapi`

so my CMakeLists.txt had to be edited to:

`target_link_libraries(${PROJECT_NAME} [other ibraries] setupapi)`
