### ISSUE TITLE
纯C++程序如何添加WM_COMM_RXCHAR消息处理函数？

### ISSUE THREAD

**Issue by liqiang311** [itas109/CSerialPort#2]
非常感谢您的代码。

我的程序是跑在后台的，写的是纯c++的代码，没有引用任何MFC的东西。我在添加WM_COMM_RXCHAR消息处理函数时遇到了困难。

请问如何在纯C++程序中添加消息处理呢？又或者能够用函数指针的方式去处理接收函数呢？

谢谢

**Comment by itas109** [comment]
可以参考一下Demo中的CSerialPortDemoWin32 这是win32编程的
