### ISSUE TITLE
eventhandler not executed

### ISSUE THREAD

**Issue by quotschmacher** [itas109/CSerialPort#20]
when i call `.readReady.connect` the connected class function never gets called, whilst using a regular `readAllData` works as expected.

i'm using vs2019. do i have to do more tha calling the connect-function?

**Comment by itas109** [comment]
`readAllData` works anytime when you called, but the ` .readReady.connect` tell you when the data come

i think you could refrenece the demo `CommNoGui` (CSerialPort\Demo\CommNoGui)

notice:
the receive class must be inheritance has_slots<> (sigslot.h usage)
```
class mySlot : public has_slots<>{...}

int main()
{
...
mySlot receive(sp);
...
sp.readReady.connect(&receive, &mySlot::OnSendMessage);
}
```

**Comment by quotschmacher** [comment]
i have a class like

`class NaClConfiguratorApplication : public MyFrame1, public has_slots<>
{
public:
        ...
	void OnReceivedSerialData();

private:
	itas109::CSerialPort m_serial_port;
};`

and i'm connecting the eventhandler with `m_serial_port.readReady.connect(this, &NaClConfiguratorApplication::OnReceivedSerialData);` but the onreceivedserialdata function never gets called, while a regular call to `readAllData` works

**Comment by itas109** [comment]
the demo CommNoGui (CSerialPort\Demo\CommNoGui)  same problem?

**Comment by quotschmacher** [comment]
tested it yesterday and the demo runs fine. i even tried to my program with yout `mySlot` class but this does not work either. 
anything i need to be carefull about when connecting the event handler?

**Comment by itas109** [comment]
Could you send the code to me? My email is itas109@qq.com

**Comment by quotschmacher** [comment]
mail is sent

**Comment by itas109** [comment]
#23 

If you call disconnect_all before readReady.connect, then the receive function will not receive data

remove disconnect_all is ok
```
//m_SerialPort.disconnect_all();
m_SerialPort.readReady.connect(this, &MainWindow::OnReceive);
```

**Comment by quotschmacher** [comment]
I used this just for testing. It didn't work before i inserted disconnect all

**Comment by itas109** [comment]
i can not run you code.

i copy your core code to `Demo\CommQT`
it does not works, remove disconnect_all is ok.

i will test it on wxwidgets when I have more time.

**Comment by quotschmacher** [comment]
just to be sure - removed the disconnect_all() and it did not work. send you the whole code via mail.

**Comment by itas109** [comment]
this version has a bug #24 :
When there are two CSerialPort classes, only last one can receive data.

so, you  could use only one CSerialPort classes to solve this problem.

---

 line 73
function ScanComPorts()
```
//itas109::CSerialPort sp;
txt_log->AppendText(sp.getVersion() + "\n");
```
change to
```
//itas109::CSerialPort sp;
txt_log->AppendText(m_serial_port.getVersion() + "\n");
```

**Comment by quotschmacher** [comment]
it works! thanks for your work!
