### ISSUE TITLE
WriteToPort 接口设计疑问

### ISSUE THREAD

**Issue by sculxp** [itas109/CSerialPort#3]
```
void CSerialPort::WriteToPort(char* string, size_t n)
{
	assert(m_hComm != 0);
	memset(m_szWriteBuffer, 0, sizeof(m_szWriteBuffer));
	memcpy(m_szWriteBuffer, string, n);
	m_nWriteSize = n;

	// set event for write
	SetEvent(m_hWriteEvent);
}
```
这样发送数据，在连续发送的时候应该是有问题的，而且也没有发现有任何通知机制能够确认上一次的数据已经发送完成，可以发送下一次的数据了．
当然　发送->等待->接收应答　这样的顺序使用应该是ok的

**Comment by itas109** [comment]
主要问题在于事件触发上，可以看一下3.0.1版的程序

**Comment by sculxp** [comment]
1. 我的需求比较简单，一问一答的协议，开个线程以阻塞方式配合超时就能满足，所以自己弄了一个．
2. 单就WriteToPort新版本的设计，WriteToPort和WriteChar同时操作m_bufferList肯定是不对的，这个list作为生产消费队列，肯定需要是线程安全的
3. 串口的接口设计我觉得还是看通信协议，一般肯定做不到网络协议那么复杂

**Comment by itas109** [comment]
作为生产消费模型来说，确实存在同时操作的问题；
其实这个串口的设计主要是更加快速的读写数据，并没有特别关心通信协议，这些工作都交给开发者去完成了

**Comment by HPChen** [comment]
有个疑问，如果我是高速发送或者接收十六进制数，而不是ASCII 格式的字符串，ReceiveStr 处理是不是就会有问题？
