### ISSUE TITLE
CSerialPort有两个地方可以改进一下

### ISSUE THREAD

**Issue by xwb1966** [itas109/CSerialPort#4]
1、WriteToPort中对m_bufferList操作需要加锁：

**Comment by xwb1966** [comment]
EnterCriticalSection(&m_csCommunicationSync);      //<----
	m_bufferList.push_back(m_bufferStruct);
	LeaveCriticalSection(&m_csCommunicationSync);     //<----
否则会导致链表被破坏，这个很容易可以模拟出来。
2、WriteChar()中，将无内容需要发送时，需要对发送信息进行reset，而不是一走了之：
if (port->m_bufferList.size() == 0) {
		ResetEvent(port->m_hWriteEvent);
}
原代码会导致一个无限死循环（并不是每次都会，具体原因不明）。现象是WaitCommEvent返回无效参数，且无法清除。

**Comment by itas109** [comment]
感谢反馈
问题1存在这个问题，这里处理当时没考虑线程安全
问题2会留意一下

**Comment by itas109** [comment]
3.0.3版本
