### ISSUE TITLE
WM_COMM_RING_DETECTED振铃信号触发两次

### ISSUE THREAD

**Issue by stormsusu** [itas109/CSerialPort#43]
VS2017，C++，打算用WM_COMM_RING_DETECTED信号来触发函数，但发现每次都会触发两次这个函数，也就是说上升沿和下降沿它都会触发，但是按理来说振铃信号应该只有一次呀，有什么办法可以设置吗？因为和该信号关联的这个事件EV_RING是自带的，不知道它指的到底是什么？请求指点 感谢~

**Comment by itas109** [comment]
这是用的CSerialPort哪个版本

可以看看相关的问题：
https://bbs.csdn.net/topics/350234500

**Comment by stormsusu** [comment]
https://download.csdn.net/download/weixin_44177837/12265880
版本的话，我在这里下载的，Serialport.h文件里最后修改时间是2018年2月
