### ISSUE TITLE
能否支持监听已打开串口？

### ISSUE THREAD

**Issue by JohnnyZhang0628** [itas109/CSerialPort#48]
你好，该项目能否支持监听已打开串口？

**Comment by itas109** [comment]
暂不支持真正意义的串口监听。如果是用CSerialPort写的串口应用，可以在接收响应函数做串口转发，来间接实现串口监听。

**Comment by JohnnyZhang0628** [comment]
好的，谢谢了。真正监听串口是不是要重写驱动啊？

**Comment by itas109** [comment]
> 好的，谢谢了。真正监听串口是不是要重写驱动啊？

是的，需要写驱动或者hook来实现

**Comment by JohnnyZhang0628** [comment]
好吧，希望能加上这个功能。
