### ISSUE TITLE
warning C4251:  : class xx needs to have dll-interface to be used by clients of class xx

### ISSUE THREAD

**Issue by itas109** [itas109/CSerialPort#58]
**Describe the bug**
warning C4251:  : class xx needs to have dll-interface to be used by clients of class xx
warning C4251: 类xx需要有 dll 接口由类xx的客户端使用

on windows visual studio 2017

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - Compiler: visual studio 2017 Community
 - Version: 4.x

**Comment by FrankCai035** [comment]
不需要啊。。
