### ISSUE TITLE
运行examples下的CommMFC工程不能接收数据

### ISSUE THREAD

**Issue by maotouying** [itas109/CSerialPort#63]
运行examples下的CommMFC工程不能接收数据，显示接收到的数据是发送的数据，借助于第三方工具，这个命令是有串口数据返回的.
![image](https://user-images.githubusercontent.com/16067208/162469368-d84f922a-7e46-421d-a099-1b04da8035ff.png)

使用第三方工具，是有数据返回的：
![image](https://user-images.githubusercontent.com/16067208/162469486-4bad4d97-ca51-4f78-bbb6-8f5b2980ff05.png)

**Comment by itas109** [comment]
数据的发送和接收是独立的。
只有在环回测试的情况下会收发相同。
建议使用虚拟串口再测试一下。

还有问题可以加QQ群沟通: [129518033](http://shang.qq.com/wpa/qunwpa?idkey=2888fa15c4513e6bfb9347052f36e437d919b2377161862948b2a49576679fc6)
