### ISSUE TITLE
波特率 可以支持 460800吗

### ISSUE THREAD

**Issue by AllofLife** [itas109/CSerialPort#67]
**描述bug**
清楚简明地描述bug
我需要支持这个波特率

**重现步骤**
描述出现bug的操作

**预期行为**
对您期望发生的事情的简洁明了的描述

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**运行环境信息:**
 - 操作系统: [e.g. DeepIn 15.11 64bit/Win7 Ultimate 64bit]
 - 编译器:[e.g. QT 5.6.2 GCC 6.3.0/VS2013 update 5]
 - 版本号[e.g. 4.0.3.200429]

**其他内容**
在此处添加有关该问题的任何其他内容

**Comment by itas109** [comment]
windows和linux下支持任意波特率
