### ISSUE TITLE
能否将此项目发布到vcpkg 包管理器上方便使用

### ISSUE THREAD

**Issue by bluceyee** [itas109/CSerialPort#68]
能否将此项目发布到vcpkg包管理上呢，以方便使用，谢谢！
 git@github.com:microsoft/vcpkg.git

**Comment by itas109** [comment]
好的，感谢反馈

**Comment by itas109** [comment]
已将CSerialPort v4.1.1版本添加到microsoft/vcpkg包管理
Added CSerialPort v4.1.1 to microsoft vcpkg package managet.

```
$ git clone https://github.com/microsoft/vcpkg
$ cd vcpkg
$ ./bootstrap-vcpkg.sh

$ ./vcpkg install cserialport
```
