### ISSUE TITLE
文档看不了

### ISSUE THREAD

**Issue by duaneya** [itas109/CSerialPort#73]
https://github.com/itas109/CSerialPort/blob/master/doc/CSerialPort_doc_cn.chm
点啥都是空白
![图片](https://user-images.githubusercontent.com/12255185/223069969-5352c5b8-4d4f-4bad-a62b-db7bdce67f59.png)

**Comment by sethome2** [comment]
![image](https://user-images.githubusercontent.com/39254204/224472570-e2ab6f24-c2b8-4ea7-97d8-4e2f1aafa898.png)
一样的问题，无法查看

**Comment by duaneya** [comment]
> ![image](https://user-images.githubusercontent.com/39254204/224472570-e2ab6f24-c2b8-4ea7-97d8-4e2f1aafa898.png) 一样的问题，无法查看

好像是win7的问题，切换为win10正常了

**Comment by duaneya** [comment]
> ![image](https://user-images.githubusercontent.com/39254204/224472570-e2ab6f24-c2b8-4ea7-97d8-4e2f1aafa898.png) 一样的问题，无法查看

右键属性，有个解除锁定，就可以看了

**Comment by sethome2** [comment]
> > ![image](https://user-images.githubusercontent.com/39254204/224472570-e2ab6f24-c2b8-4ea7-97d8-4e2f1aafa898.png) 一样的问题，无法查看
> 
> 右键属性，有个解除锁定，就可以看了

好的，谢谢，可以了
