### ISSUE TITLE
求助，高波特率下通信相应不到很快的信号有什么可能解决方案吗？

### ISSUE THREAD

**Issue by Ke351** [itas109/CSerialPort#74]
需要通讯的设备波特率锁死在921600，在我从主机输出一个指令后，他会立马返回另一个指令，经过串口调试器检测没有问题。然后我使用example中noGUI的例程来尝试接收，但是MyListener完全没有相应到信号，我已经排除了无法发出信号的问题，应该是没法快速接收的问题（用其他设备测试了9600波特率下可以接收），关于这个问题有没有好点的解决方案。

**Comment by itas109** [comment]
数据不正常可以开启日志看一下啥问题
可能和读取超时有关

#define CSERIALPORT_DEBUG

https://itas109.blog.csdn.net/article/details/129250464

或者可以加qq群沟通129518033
