### ISSUE TITLE
Mac枚举串口列表失败，getSerialPath有Bug

### ISSUE THREAD

**Issue by xxCabin** [itas109/CSerialPort#75]
/**描述bug**
Mac枚举串口失败
`char *getSerialPath(char *dest, io_object_t &serialPort)
{
    CFTypeRef calloutCFString;

    calloutCFString = IORegistryEntryCreateCFProperty(serialPort, CFSTR(kIOCalloutDeviceKey), kCFAllocatorDefault, 0);

    if (calloutCFString)
    {
        // sizeof(dest) = 8bytes, can not copy all bytes
        // CFStringGetCString(static_cast<CFStringRef>(calloutCFString), dest, sizeof(dest), kCFStringEncodingUTF8);

        CFStringGetCString(static_cast<CFStringRef>(calloutCFString), dest, MAXPATHLEN, kCFStringEncodingUTF8);

        CFRelease(calloutCFString);
    }

    return dest;
}`

**重现步骤**
mac下，调用getPortInfoList
**预期行为**
无
**截图**
![image](https://github.com/itas109/CSerialPort/assets/24838327/f70f0d64-76b9-476b-95ad-7713558f1315)

**运行环境信息:**
 - 操作系统: mac12.6.3
 - 编译器:xcode 14.0
 - 版本号：v4.3.0

**其他内容**
无

**Comment by itas109** [comment]
感谢反馈，可以加群交流
