### ISSUE TITLE
Linux版本同步模式写数据后，再读不成功

### ISSUE THREAD

**Issue by yinzk0619** [itas109/CSerialPort#80]
**描述bug**
Linux版本同步模式写数据后，再读不成功，卡死

**重现步骤**
1.设置串口信息，打开串口，设置串口为同步模式；
2.往串口写一段数据；
3.串口马上返回响应的数据；
3.sleep 500毫秒；
4.再读取数据，不能正常返回，卡死；

**预期行为**
正常读取串口返回的数据

**运行环境信息:**
 - 操作系统: 麒麟 SP V10
 - 编译器: inter i5

**其他内容**
Linux情况下 commThreadMonitor 这个线程处理函数，在同步模式下，在检测到有数据可读时，直接将串口中的数据读取了，导致正常读数据，在sleep一段时间后，没有数据可读取了，一直卡死，这个应该是同步模式不启动读取功能；

**Comment by itas109** [comment]
感谢反馈，加Q群129518033沟通效率更高
