### ISSUE TITLE
Is there a way to know if an open port is diconnected

### ISSUE THREAD

**Issue by Risu-swift** [itas109/CSerialPort#91]
I want to know if there is a way to identify if an open port is disconnected and reopen the port if it is available again.

Currently the method I thought I will use is `CSerialPortInfo` to check if the port exists and close the port if it doesnt and reopen the port once the port is available

My question is there any better way to do this ?

**Comment by itas109** [comment]
This project may help on windows.

https://github.com/itas109/CSerialPortExtend/tree/master/hotSwap
